opcodeDatabase = {
# CATEGORIES
    # Motion (Incomplete)
    # Looks (Incomplete)
    # Sound (Incomplete)
    # Events (Incomplete)
        # Events: Keys
        "event_whenkeypressed": {
            "type": "hat",
            "category": "Events",
            "newOpcode": "when [KEY_OPTION] key pressed",
            "inputTypes": {},
            "optionTypes": {"KEY_OPTION": "key"},
        },
        "event_whenbroadcastreceived": {
            "type": "hat",
            "category": "Events",
            "newOpcode": "when i receive [BROADCAST_OPTION]",
            "inputTypes": {},
            "optionTypes": {"BROADCAST_OPTION": "broadcast"},
        },
        "event_broadcast": {
            "type": "instruction",
            "category": "Events",
            "newOpcode": "broadcast [BROADCAST]",
            "inputTypes": {"BROADCAST": "broadcast"},
            "inputTranslation": {"BROADCAST_INPUT": "BROADCAST"},
            "optionTypes": {},
        },
    # Control (Incomplete)
        "control_if": {
            "type": "instruction",
            "category": "Control",
            "newOpcode": "if <CONDITION> then {THEN}",
            "inputTypes": {"CONDITION": "boolean", "THEN": "script"},
            "inputTranslation": {"SUBSTACK": "THEN"},
            "optionTypes": {},
        },
        "control_if_else": {
            "type": "instruction",
            "category": "Control",
            "newOpcode": "if <CONDITION> then {THEN} else {ELSE}",
            "inputTypes": {"CONDITION": "boolean", "THEN": "script", "ELSE": "script"},
            "inputTranslation": {"SUBSTACK": "THEN", "SUBSTACK2": "ELSE"},
            "optionTypes": {},
        },
        "control_switch": {
            "type": "instruction",
            "category": "Control",
            "newOpcode": "switch (CONDITION) {CASES}",
            "inputTypes": {"CONDITION": "text", "CASES": "script"},
            "inputTranslation": {"SUBSTACK": "CASES"},
            "optionTypes": {},
        },
        "control_switch_default": {
            "type": "instruction",
            "category": "Control",
            "newOpcode": "switch (CONDITION) {SUBSTACK1} default {SUBSTACK2}",
            "inputTypes": {"CONDITION": "text", "SUBSTACK1": "script", "SUBSTACK2": "script"},
            "optionTypes": {},
        },
        "control_case": {
            "type": "instruction",
            "category": "Control",
            "newOpcode": "case (CONDITION) {BODY}",
            "inputTypes": {"CONDITION": "text", "BODY": "script"},
            "inputTranslation": {"SUBSTACK": "BODY"},
            "optionTypes": {},
        },
        "control_repeat": {
            "type": "instruction",
            "category": "Control",
            "newOpcode": "repeat (TIMES) {SUBSTACK}",
            "inputTypes": {"TIMES": "number", "SUBSTACK": "script"},
            "optionTypes": {},
        },
    # Sensing (Incomplete)
    # Operators (Incomplete)
        # Operators: Math Part 1
        "operator_add": {
            "type": "textReporter",
            "category": "Operators",
            "newOpcode": "(NUM1) + (NUM2)",
            "inputTypes": {"NUM1": "number", "NUM2": "number"},
            "optionTypes": {},
        },
        "operator_subtract": {
            "type": "textReporter",
            "category": "Operators",
            "newOpcode": "(NUM1) - (NUM2)",
            "inputTypes": {"NUM1": "number", "NUM2": "number"},
            "optionTypes": {},
        },
        "operator_multiply": {
            "type": "textReporter",
            "category": "Operators",
            "newOpcode": "(NUM1) * (NUM2)",
            "inputTypes": {"NUM1": "number", "NUM2": "number"},
            "optionTypes": {},
        },
        "operator_divide": {
            "type": "textReporter",
            "category": "Operators",
            "newOpcode": "(NUM1) / (NUM2)",
            "inputTypes": {"NUM1": "number", "NUM2": "number"},
            "optionTypes": {},
        },
#TODO: add option translation: OPTION -> OPERATION
        "operator_advMath": {
            "type": "textReporter",
            "category": "Operators",
            "newOpcode": "(NUM1) [OPTION] (NUM2)",
            "inputTypes": {"NUM1": "number", "NUM2": "number"},
            "inputTranslation": {"ONE": "NUM1", "TWO": "NUM2"},
            "optionTypes": {"OPTION": "math operation"},
        },
        "operator_random": {
            "type": "textReporter",
            "category": "Operators",
            "newOpcode": "pick random (NUM1) to (NUM2)",
            "inputTypes": {"NUM1": "number", "NUM2": "number"},
            "inputTranslation": {"FROM": "NUM1", "TO": "NUM2"},
            "optionTypes": {},
        },
        "operator_constrainnumber": {
            "type": "textReporter",
            "category": "Operators",
            "newOpcode": "constrain (NUM) min (MIN) max (MAX)",
            "inputTypes": {"NUM": "number", "MIN": "number", "MAX": "number"},
            "inputTranslation": {"inp": "NUM", "min": "MIN", "max": "MAX"},
            "optionTypes": {},
        },
        "operator_lerpFunc": {
            "type": "textReporter",
            "category": "Operators",
            "newOpcode": "interpolate (NUM1) to (NUM2) by (WEIGHT)",
            "inputTypes": {"NUM1": "number", "NUM2": "number", "WEIGHT": "number"},
            "inputTranslation": {"ONE": "NUM1", "TWO": "NUM2", "AMOUNT": "WEIGHT"},
            "optionTypes": {},
        },
        # Operators: Comparators
        "operator_gt": {
            "type": "booleanReporter",
            "category": "Operators",
            "newOpcode": "(OPERAND1) = (OPERAND2)",
            "inputTypes": {"OPERAND1": "text", "OPERAND2": "text"},
            "optionTypes": {},
        },
        "operator_gtorequal": {
            "type": "booleanReporter",
            "category": "Operators",
            "newOpcode": "(OPERAND1) >= (OPERAND2)",
            "inputTypes": {"OPERAND1": "text", "OPERAND2": "text"},
            "optionTypes": {},
        },
        "operator_lt": {
            "type": "booleanReporter",
            "category": "Operators",
            "newOpcode": "(OPERAND1) < (OPERAND2)",
            "inputTypes": {"OPERAND1": "text", "OPERAND2": "text"},
            "optionTypes": {},
        },
        "operator_ltorequal": {
            "type": "booleanReporter",
            "category": "Operators",
            "newOpcode": "(OPERAND1) <= (OPERAND2)",
            "inputTypes": {"OPERAND1": "text", "OPERAND2": "text"},
            "optionTypes": {},
        },
        "operator_equals": {
            "type": "booleanReporter",
            "category": "Operators",
            "newOpcode": "(OPERAND1) = (OPERAND2)",
            "inputTypes": {"OPERAND1": "text", "OPERAND2": "text"},
            "optionTypes": {},
        },
        "operator_notequal": {
            "type": "booleanReporter",
            "category": "Operators",
            "newOpcode": "(OPERAND1) != (OPERAND2)",
            "inputTypes": {"OPERAND1": "text", "OPERAND2": "text"},
            "optionTypes": {},
        },        
        # Operators: True and False
        "operator_trueBoolean": {
            "type": "booleanReporter",
            "category": "Operators",
            "newOpcode": "true",
            "inputTypes": {},
            "optionTypes": {},
        },
        "operator_falseBoolean": {
            "type": "booleanReporter",
            "category": "Operators",
            "newOpcode": "false",
            "inputTypes": {},
            "optionTypes": {},
        },
        # Operators: Boolean Algebra
        "operator_and": {
            "type": "booleanReporter",
            "category": "Operators",
            "newOpcode": "<OPERAND1> and <OPERAND2>",
            "inputTypes": {"OPERAND1": "boolean", "OPERAND2": "boolean"},
            "optionTypes": {},
        },
        "operator_or": {
            "type": "booleanReporter",
            "category": "Operators",
            "newOpcode": "<OPERAND1> or <OPERAND2>",
            "inputTypes": {"OPERAND1": "boolean", "OPERAND2": "boolean"},
            "optionTypes": {},
        },
        "operator_not": {
            "type": "booleanReporter",
            "category": "Operators",
            "newOpcode": "not <OPERAND>",
            "inputTypes": {"OPERAND": "boolean"},
            "optionTypes": {},
        },
        # Operators: Newline and Tab
        "operator_newLine": {
            "type": "textReporter",
            "category": "Operators",
            "newOpcode": "new line",
            "inputTypes": {},
            "optionTypes": {},
        },
        "operator_tabCharacter": {
            "type": "textReporter",
            "category": "Operators",
            "newOpcode": "tab character",
            "inputTypes": {},
            "optionTypes": {},
        },
        # Operators: Text Manipulation
        "operator_join": {
            "type": "textReporter",
            "category": "Operators",
            "newOpcode": "join (STRING1) (STRING2)",
            "inputTypes": {"STRING1": "text", "STRING2": "text"},
            "optionTypes": {},
        },
        "operator_join3": {
            "type": "textReporter",
            "category": "Operators",
            "newOpcode": "join (STRING1) (STRING2) (STRING3)",
            "inputTypes": {"STRING1": "text", "STRING2": "text", "STRING3": "text"},
            "optionTypes": {},
        },
        "operator_indexOfTextInText": {
            "type": "textReporter",
            "category": "Operators",
            "newOpcode": "index of (SUBSTRING) in (TEXT)",
            "inputTypes": {"SUBSTRING": "text", "STRING": "text"},
            "inputTranslation": {"TEXT1": "SUBSTRING", "TEXT2": "TEXT"},
            "optionTypes": {},
        },
        "operator_lastIndexOfTextInText": {
            "type": "textReporter",
            "category": "Operators",
            "newOpcode": "last index of (SUBSTRING) in (TEXT)",
            "inputTypes": {"SUBSTRING": "text", "STRING": "text"},
            "inputTranslation": {"TEXT1": "SUBSTRING", "TEXT2": "TEXT"},
            "optionTypes": {},
        },
        "operator_letter_of": {
            "type": "textReporter",
            "category": "Operators",
            "newOpcode": "letter (LETTER) of (STRING)",
            "inputTypes": {"LETTER": "positive integer", "STRING": "text"},
            "optionTypes": {},
        },
        "operator_getLettersFromIndexToIndexInText": {
            "type": "textReporter",
            "category": "Operators",
            "newOpcode": "letters from (START) to (STOP) in (TEXT)",
            "inputTypes": {"START": "positive integer", "STOP": "text", "TEXT": "text"},
            "inputTranslation": {"INDEX1": "START", "INDEX2": "STOP"},
            "optionTypes": {},
        },
        # Operators: Math Part 2
        "operator_mod": {
            "type": "textReporter",
            "category": "Operators",
            "newOpcode": "(NUM1) mod (NUM2)",
            "inputTypes": {"NUM1": "text", "NUM2": "text"},
            "optionTypes": {},
        },
        
        
        "operator_boolify": {
            "type": "booleanReporter",
            "category": "Operators",
            "newOpcode": "(VALUE) as a boolean",
            "inputTypes": {"VALUE": "text"},
            "inputTranslation":  {"ONE": "VALUE"},
            "optionTypes": {},
        },
    # Variables
        "data_setvariableto": {
            "type": "instruction",
            "category": "Variables",
            "newOpcode": "set [VARIABLE] to (VALUE)",
            "inputTypes": {"VALUE": "text"},
            "optionTypes": {"VARIABLE": "variable"},
        },
        "data_changevariableby": {
            "type": "instruction",
            "category": "Variables",
            "newOpcode": "change [VARIABLE] by (VALUE)",
            "inputTypes": {"VALUE": "number"},
            "optionTypes": {"VARIABLE": "variable"},
        },
        "data_showvariable": {
            "type": "instruction",
            "category": "Variables",
            "newOpcode": "show variable [VARIABLE]",
            "inputTypes": {},
            "optionTypes": {"VARIABLE": "variable"},
        },
        "data_hidevariable": {
            "type": "instruction",
            "category": "Variables",
            "newOpcode": "hide variable [VARIABLE]",
            "inputTypes": {},
            "optionTypes": {"VARIABLE": "variable"},
        },
    # Lists
        "data_addtolist": {
            "type": "instruction",
            "category": "Lists",
            "newOpcode": "add (ITEM) to [LIST]",
            "inputTypes": {"ITEM": "text"},
            "optionTypes": {"LIST": "list"},
        },
        "data_deleteoflist": {
            "type": "instruction",
            "category": "Lists",
            "newOpcode": "delete (INDEX) of [LIST]",
            "inputTypes": {"INDEX": "integer"},
            "optionTypes": {"LIST": "list"},
        },
        "data_deletealloflist": {
            "type": "instruction",
            "category": "Lists",
            "newOpcode": "delete all of [LIST]",
            "inputTypes": {},
            "optionTypes": {"LIST": "list"},
        },
        "data_shiftlist": {
            "type": "instruction",
            "category": "Lists",
            "newOpcode": "shift [LIST] by (INDEX)",
            "inputTypes": {"INDEX": "integer"},
            "optionTypes": {"LIST": "list"},
        },
        "data_insertatlist": {
            "type": "instruction",
            "category": "Lists",
            "newOpcode": "insert (ITEM) at (INDEX) of [LIST]",
            "inputTypes": {"ITEM": "text", "INDEX": "integer"},
            "optionTypes": {"LIST": "list"},
        },
        "data_replaceitemoflist": {
            "type": "instruction",
            "category": "Lists",
            "newOpcode": "replace item (INDEX) of [LIST] with (ITEM)",
            "inputTypes": {"INDEX": "integer", "ITEM": "text"},
            "optionTypes": {"LIST": "list"},
        },
        "data_listforeachitem": {
            "type": "instruction",
            "category": "Lists",
            "newOpcode": "For each item [VARIABLE] in [LIST] {BODY}",
            "inputTypes": {"BODY": "script"},
            "inputTranslation": {"SUBSTACK": "BODY"},
            "optionTypes": {"VARIABLE": "variable", "LIST": "list"},
        },
        "data_listforeachnum": {
            "type": "instruction",
            "category": "Lists",
            "newOpcode": "For each item # [VARIABLE] in [LIST] {BODY}",
            "inputTypes": {"BODY": "script"},
            "inputTranslation": {"SUBSTACK": "BODY"},
            "optionTypes": {"VARIABLE": "variable", "LIST": "list"},
        },
        "data_itemoflist": {
            "type": "textReporter",
            "category": "Lists",
            "newOpcode": "item (INDEX) of [LIST]",
            "inputTypes": {"INDEX": "integer"},
            "optionTypes": {"LIST": "list"},
        },
        "data_itemnumoflist": {
            "type": "textReporter",
            "category": "Lists",
            "newOpcode": "item # of (ITEM) in [LIST]",
            "inputTypes": {"ITEM": "text"},
            "optionTypes": {"LIST": "list"},
        },
        "data_amountinlist": {
            "type": "textReporter",
            "category": "Lists",
            "newOpcode": "amount of (VALUE) of [LIST]",
            "inputTypes": {"VALUE": "text"},
            "optionTypes": {"LIST": "list"},
        },
        "data_lengthoflist": {
            "type": "textReporter",
            "category": "Lists",
            "newOpcode": "length of [LIST]",
            "inputTypes": {},
            "optionTypes": {"LIST": "list"},
        },
        "data_listcontainsitem": {
            "type": "booleanReporter",
            "category": "Lists",
            "newOpcode": "[LIST] contains (ITEM) ?",
            "inputTypes": {"ITEM": "text"},
            "optionTypes": {"LIST": "list"},
        },
        "data_itemexistslist": {
            "type": "booleanReporter",
            "category": "Lists",
            "newOpcode": "item (INDEX) exists in [LIST] ?",
            "inputTypes": {"INDEX": "integer"},
            "optionTypes": {"LIST": "list"},
        },
        "data_listisempty": {
            "type": "booleanReporter",
            "category": "Lists",
            "newOpcode": "is [LIST] empty?",
            "inputTypes": {},
            "optionTypes": {"LIST": "list"},
        },
        "data_reverselist": {
            "type": "instruction",
            "category": "Lists",
            "newOpcode": "reverse [LIST]",
            "inputTypes": {},
            "optionTypes": {"LIST": "list"},
        },
        "data_arraylist": {
            "type": "instruction",
            "category": "Lists",
            "newOpcode": "set [LIST] to array (VALUE)",
            "inputTypes": {"VALUE": "text"},
            "optionTypes": {"LIST": "list"},
        },
        "data_listarray": {
            "type": "instruction",
            "category": "Lists",
            "newOpcode": "get list [LIST] as an array",
            "inputTypes": {},
            "optionTypes": {"LIST": "list"},
        },
        "data_showlist": {
            "type": "instruction",
            "category": "Lists",
            "newOpcode": "show list [LIST]",
            "inputTypes": {},
            "optionTypes": {"LIST": "list"},
        },
        "data_hidelist": {
            "type": "instruction",
            "category": "Lists",
            "newOpcode": "hide list [LIST]",
            "inputTypes": {},
            "optionTypes": {"LIST": "list"},
        },
        
# EXTENSIONS (Incomplete)
    # JSON (jgJSON) (Incomplete)
        # JSON: Objects
        "jgJSON_getValueFromJSON": {
            "type": "textReporter",
            "category": "JSON",
            "newOpcode": "get (VALUE) from (JSON)",
            "inputTypes": {"VALUE": "text", "JSON": "text"},
            "optionTypes": {},
        },
        "jgJSON_setValueToKeyInJSON": {
            "type": "textReporter",
            "category": "JSON",
            "newOpcode": "set (KEY) to (VALUE) in (JSON)",
            "inputTypes": {"KEY": "text", "VALUE": "text", "JSON": "text"},
            "optionTypes": {},
        },
        # JSON: Arrays
        "jgJSON_json_array_push": {
            "type": "textReporter",
            "category": "JSON",
            "newOpcode": "in array (array) add (item)",
            "inputTypes": {"array": "text", "item": "text"},
            "optionTypes": {},
        },
        "jgJSON_json_array_get": {
            "type": "textReporter",
            "category": "JSON",
            "newOpcode": "in array (array) get (index)",
            "inputTypes": {"array": "text", "index": "number"},
            "optionTypes": {},
        },
        "jgJSON_json_array_length": {
            "type": "textReporter",
            "category": "JSON",
            "newOpcode": "length of array (array)",
            "inputTypes": {"array": "text"},
            "optionTypes": {},
        },
        "jgJSON_json_array_contains": {
            "type": "booleanReporter",
            "category": "JSON",
            "newOpcode": "array (array) contains (value) ?",
            "inputTypes": {"array": "text", "value": "text"},
            "optionTypes": {},
        },
    # SPECIAL
        # SPECIAL: Varibles and Lists
        "special_variable_value": {
            "type": "textReporter",
            "category": "Variables",
            "newOpcode": "value of [VARIABLE]",
            "inputTypes": {},
            "optionTypes": {"VARIABLE": "variable"},
        },
        "special_list_value": {
            "type": "textReporter",
            "category": "Lists",
            "newOpcode": "value of [LIST]",
            "inputTypes": {},
            "optionTypes": {"LIST": "list"},
        },
        # SPECIAL: Custom Blocks
        "special_define": {
            "type": "hat",
            "category": "My Blocks",
            "newOpcode": "define ...",
            "inputTypes": {},
            "optionTypes": {"noScreenRefresh": "boolean", "blockType": "blockType", "customOpcode": "opcode"},
        },
        "procedures_call": {
            "type": "dynamic",
            "category": "My Blocks",
            "newOpcode": "call ...",
            "inputTypes": {},
            "optionTypes": {"customOpcode": "opcode"},
        },
        "procedures_return": {
            "type": "lastInstruction",
            "category": "My Blocks",
            "newOpcode": "return (return)",
            "inputTypes": {"return": "text"},
            "optionTypes": {},
        },
        "procedures_set": {
            "type": "instruction",
            "category": "My Blocks",
            "newOpcode": "set (PARAM) to (VALUE)",
            "inputTypes": {"PARAM": "round", "VALUE": "text"},
            "optionTypes": {},
        },
        "argument_reporter_string_number": {
            "type": "textReporter",
            "category": None,
            "newOpcode": "value of text argument [VALUE]",
            "inputTypes": {},
            "optionTypes": {"VALUE": "string"},
        },
        "argument_reporter_boolean": {
            "type": "booleanReporter",
            "category": None,
            "newOpcode": "value of boolean argument [VALUE]",
            "inputTypes": {},
            "optionTypes": {"VALUE": "string"},
        },       
}

inputDefault = {}
inputBlockDefault = None
inputTextDefault = ""
inputBlocksDefault = []
optionDefault = {}
commentDefault = None

inputModes = {
    "broadcast"       : "block-and-text",
    "integer"         : "block-and-text",
    "positive integer": "block-and-text",
    "number"          : "block-and-text",
    "text"            : "block-and-text",
    "boolean"         : "block-only",
    "round"           : "block-only",
    "script"          : "script",
}