data = {
 'I': {'opcode': 'motion_movesteps',
       'next': 'h',
       'parent': None,
       'inputs': {'STEPS': [1, [4, '10']]},
       'fields': {},
       'shadow': False,
       'topLevel': True,
       'x': 264,
       'y': 139},
 'h': {'opcode': 'motion_movebacksteps',
       'next': 'i',
       'parent': 'I',
       'inputs': {'STEPS': [1, [4, '10']]},
       'fields': {},
       'shadow': False,
       'topLevel': False},
 'i': {'opcode': 'motion_moveupdownsteps',
       'next': 'j',
       'parent': 'h',
       'inputs': {'STEPS': [1, [4, '10']]},
       'fields': {'DIRECTION': ['up', 'z~@c)kG(CJ/qdF_eaWq5']},
       'shadow': False,
       'topLevel': False},
 'j': {'opcode': 'motion_turnright',
       'next': 'k',
       'parent': 'i',
       'inputs': {'DEGREES': [1, [4, '15']]},
       'fields': {},
       'shadow': False,
       'topLevel': False},
 'k': {'opcode': 'motion_turnleft',
       'next': 'a',
       'parent': 'j',
       'inputs': {'DEGREES': [1, [4, '15']]},
       'fields': {},
       'shadow': False,
       'topLevel': False},
 'a': {'opcode': 'motion_goto',
       'next': 'b',
       'parent': 'k',
       'inputs': {'TO': [1, 'J']},
       'fields': {},
       'shadow': False,
       'topLevel': False},
 'J': {'opcode': 'motion_goto_menu',
       'next': None,
       'parent': 'a',
       'inputs': {},
       'fields': {'TO': ['_random_', 'ZEm{)CxMh?|GQ2d(X,YL']},
       'shadow': True,
       'topLevel': False},
 'b': {'opcode': 'motion_goto',
       'next': 'l',
       'parent': 'a',
       'inputs': {'TO': [1, 'K']},
       'fields': {},
       'shadow': False,
       'topLevel': False},
 'K': {'opcode': 'motion_goto_menu',
       'next': None,
       'parent': 'b',
       'inputs': {},
       'fields': {'TO': ['_mouse_', '@[5eSv)Lv_pGH/6au@N6']},
       'shadow': True,
       'topLevel': False},
 'l': {'opcode': 'motion_gotoxy',
       'next': 'm',
       'parent': 'b',
       'inputs': {'X': [1, [4, '0']], 'Y': [1, [4, '0']]},
       'fields': {},
       'shadow': False,
       'topLevel': False},
 'm': {'opcode': 'motion_changebyxy',
       'next': 'c',
       'parent': 'l',
       'inputs': {'DX': [1, [4, '10']], 'DY': [1, [4, '10']]},
       'fields': {},
       'shadow': False,
       'topLevel': False},
 'c': {'opcode': 'motion_glideto',
       'next': 'd',
       'parent': 'm',
       'inputs': {'SECS': [1, [4, '1']], 'TO': [1, 'L']},
       'fields': {},
       'shadow': False,
       'topLevel': False},
 'L': {'opcode': 'motion_glideto_menu',
       'next': None,
       'parent': 'c',
       'inputs': {},
       'fields': {'TO': ['_random_', 'ON3dy,T/Y^8^^*0M%EjY']},
       'shadow': True,
       'topLevel': False},
 'd': {'opcode': 'motion_glideto',
       'next': 'n',
       'parent': 'c',
       'inputs': {'SECS': [1, [4, '1']], 'TO': [1, 'M']},
       'fields': {},
       'shadow': False,
       'topLevel': False},
 'M': {'opcode': 'motion_glideto_menu',
       'next': None,
       'parent': 'd',
       'inputs': {},
       'fields': {'TO': ['_mouse_', 'Vq85X8z^1shd{4+*xc]5']},
       'shadow': True,
       'topLevel': False},
 'n': {'opcode': 'motion_pointindirection',
       'next': 'e',
       'parent': 'd',
       'inputs': {'DIRECTION': [1, [8, '90']]},
       'fields': {},
       'shadow': False,
       'topLevel': False},
 'e': {'opcode': 'motion_pointtowards',
       'next': 'o',
       'parent': 'n',
       'inputs': {'TOWARDS': [1, 'N']},
       'fields': {},
       'shadow': False,
       'topLevel': False},
 'N': {'opcode': 'motion_pointtowards_menu',
       'next': None,
       'parent': 'e',
       'inputs': {},
       'fields': {'TOWARDS': ['_mouse_', 'RSt3X|BI]`DeE/y}DHE1']},
       'shadow': True,
       'topLevel': False},
 'o': {'opcode': 'motion_pointtowardsxy',
       'next': 'p',
       'parent': 'e',
       'inputs': {'X': [1, [4, '0']], 'Y': [1, [4, '0']]},
       'fields': {},
       'shadow': False,
       'topLevel': False},
 'p': {'opcode': 'motion_turnaround',
       'next': 'q',
       'parent': 'o',
       'inputs': {},
       'fields': {},
       'shadow': False,
       'topLevel': False},
 'q': {'opcode': 'motion_changexby',
       'next': 'r',
       'parent': 'p',
       'inputs': {'DX': [1, [4, '10']]},
       'fields': {},
       'shadow': False,
       'topLevel': False},
 'r': {'opcode': 'motion_setx',
       'next': 's',
       'parent': 'q',
       'inputs': {'X': [1, [4, '83']]},
       'fields': {},
       'shadow': False,
       'topLevel': False},
 's': {'opcode': 'motion_changeyby',
       'next': 't',
       'parent': 'r',
       'inputs': {'DY': [1, [4, '10']]},
       'fields': {},
       'shadow': False,
       'topLevel': False},
 't': {'opcode': 'motion_sety',
       'next': 'u',
       'parent': 's',
       'inputs': {'Y': [1, [4, '39']]},
       'fields': {},
       'shadow': False,
       'topLevel': False},
 'u': {'opcode': 'motion_ifonedgebounce',
       'next': 'f',
       'parent': 't',
       'inputs': {},
       'fields': {},
       'shadow': False,
       'topLevel': False},
 'f': {'opcode': 'motion_ifonspritebounce',
       'next': 'g',
       'parent': 'u',
       'inputs': {'SPRITE': [1, 'O']},
       'fields': {},
       'shadow': False,
       'topLevel': False},
 'O': {'opcode': 'motion_pointtowards_menu',
       'next': None,
       'parent': 'f',
       'inputs': {},
       'fields': {'TOWARDS': ['_mouse_', 'sva(Ue(QAUvRw02]k`pq']},
       'shadow': True,
       'topLevel': False},
 'g': {'opcode': 'motion_ifonspritebounce',
       'next': 'v',
       'parent': 'f',
       'inputs': {'SPRITE': [1, 'P']},
       'fields': {},
       'shadow': False,
       'topLevel': False},
 'P': {'opcode': 'motion_pointtowards_menu',
       'next': None,
       'parent': 'g',
       'inputs': {},
       'fields': {'TOWARDS': ['_random_', ']aA{^(x-5Ov]{{UFl8?I']},
       'shadow': True,
       'topLevel': False},
 'v': {'opcode': 'motion_setrotationstyle',
       'next': 'w',
       'parent': 'g',
       'inputs': {},
       'fields': {'STYLE': ['left-right', ':%45l!su+q/uN]))r1wY']},
       'shadow': False,
       'topLevel': False},
 'w': {'opcode': 'motion_setrotationstyle',
       'next': 'x',
       'parent': 'v',
       'inputs': {},
       'fields': {'STYLE': ['up-down', 'e^7X^[s-IpaXbU*Khbh@']},
       'shadow': False,
       'topLevel': False},
 'y': {'opcode': 'motion_setrotationstyle',
       'next': 'z',
       'parent': 'x',
       'inputs': {},
       'fields': {'STYLE': ["don't rotate", '/OdJ)_K%+2bB%2.g*c=O']},
       'shadow': False,
       'topLevel': False},
 'x': {'opcode': 'motion_setrotationstyle',
       'next': 'y',
       'parent': 'w',
       'inputs': {},
       'fields': {'STYLE': ['look at', '4ffs]urJb%R@G.rJbH6^']},
       'shadow': False,
       'topLevel': False},
 'z': {'opcode': 'motion_setrotationstyle',
       'next': 'A',
       'parent': 'y',
       'inputs': {},
       'fields': {'STYLE': ['all around', 'z3nB#F|97^@a(mtvXbw_']},
       'shadow': False,
       'topLevel': False},
 'A': {'opcode': 'motion_move_sprite_to_scene_side',
       'next': 'B',
       'parent': 'z',
       'inputs': {},
       'fields': {'ALIGNMENT': ['bottom-left', 'GV8khiyanp1ZZ?SZ2m+!']},
       'shadow': False,
       'topLevel': False},
 'B': {'opcode': 'motion_move_sprite_to_scene_side',
       'next': 'C',
       'parent': 'A',
       'inputs': {},
       'fields': {'ALIGNMENT': ['bottom', ';:`,#Y]*J^)dh^@w?g~F']},
       'shadow': False,
       'topLevel': False},
 'C': {'opcode': 'motion_move_sprite_to_scene_side',
       'next': 'D',
       'parent': 'B',
       'inputs': {},
       'fields': {'ALIGNMENT': ['bottom-right', 'y!^TLqm-0.V*pq{nU(}-']},
       'shadow': False,
       'topLevel': False},
 'D': {'opcode': 'motion_move_sprite_to_scene_side',
       'next': 'E',
       'parent': 'C',
       'inputs': {},
       'fields': {'ALIGNMENT': ['top-left', '6V@n.~#=4_9GtA*m,QyF']},
       'shadow': False,
       'topLevel': False},
 'E': {'opcode': 'motion_move_sprite_to_scene_side',
       'next': 'F',
       'parent': 'D',
       'inputs': {},
       'fields': {'ALIGNMENT': ['top-left', ':86+z4cZToMi0_;^LopB']},
       'shadow': False,
       'topLevel': False},
 'F': {'opcode': 'motion_move_sprite_to_scene_side',
       'next': 'G',
       'parent': 'E',
       'inputs': {},
       'fields': {'ALIGNMENT': ['top', '97|BXKFLe!s#?K9Z]Pd,']},
       'shadow': False,
       'topLevel': False},
 'G': {'opcode': 'motion_move_sprite_to_scene_side',
       'next': 'H',
       'parent': 'F',
       'inputs': {},
       'fields': {'ALIGNMENT': ['top-right', 'eGDD}tlTRq=mLbiEhI]G']},
       'shadow': False,
       'topLevel': False},
 'H': {'opcode': 'motion_move_sprite_to_scene_side',
       'next': 'Q',
       'parent': 'G',
       'inputs': {},
       'fields': {'ALIGNMENT': ['left', 'VFE~pv0:di=?A%,`n/Vr']},
       'shadow': False,
       'topLevel': False},
 'Q': {'opcode': 'motion_move_sprite_to_scene_side',
       'next': None,
       'parent': 'H',
       'inputs': {},
       'fields': {'ALIGNMENT': ['right', 'UO+%/uiYo=3Cp_*DFf9-']},
       'shadow': False,
       'topLevel': False},
 'R': {'opcode': 'motion_xposition',
       'next': None,
       'parent': None,
       'inputs': {},
       'fields': {},
       'shadow': False,
       'topLevel': True,
       'x': 304,
       'y': 1932},
 'S': {'opcode': 'motion_yposition',
       'next': None,
       'parent': None,
       'inputs': {},
       'fields': {},
       'shadow': False,
       'topLevel': True,
       'x': 300,
       'y': 1999},
 'T': {'opcode': 'motion_direction',
       'next': None,
       'parent': None,
       'inputs': {},
       'fields': {},
       'shadow': False,
       'topLevel': True,
       'x': 284,
       'y': 2084}}

from pprint import pprint
opcode_inputs = {}
for key, value in zip(data.keys(), data.values()):
    if value["opcode"] not in opcode_inputs:
        opcode_inputs[value["opcode"]] = value["inputs"]
    else:
        opcode_inputs[value["opcode"]] |= value["inputs"]
pprint(list(opcode_inputs.keys()))