A = [
    {"position": [0, 0],
 "blocks": [{"opcode": "when green flag clicked", "inputs": {}, "options": {}},
            {"opcode": "set [VARIABLE] to (VALUE)",
             "inputs": {"VALUE": {"block": None, "text": "0"}},
             "options": {"VARIABLE": "score"}},
            {"opcode": "say (MESSAGE) for (SECONDS) seconds",
             "inputs": {"MESSAGE": {"block": None,
                                    "text": "Click to increase score!"},
                        "SECONDS": {"block": None, "text": "2"}},
             "options": {}},
            {"opcode": "wait (SECONDS) seconds",
             "inputs": {"SECONDS": {"block": None, "text": "1"}},
             "options": {}},
            {"opcode": "change [VARIABLE] by (VALUE)",
             "inputs": {"VALUE": {"block": None, "text": "1"}},
             "options": {"VARIABLE": "score"}},
            {"opcode": "say (MESSAGE) for (SECONDS) seconds",
             "inputs": {"MESSAGE": {"block": {"opcode": "join (STRING1) "
                                                        "(STRING2)",
                                              "inputs": {"STRING1": {"block": None,
                                                                     "text": "Score: "},
                                                         "STRING2": {"block": {"opcode": "value "
                                                                                         "of "
                                                                                         "[VARIABLE]",
                                                                               "inputs": {},
                                                                               "options": {"VARIABLE": "score"}},
                                                                     "text": ""}},
                                              "options": {}},
                                    "text": ""},
                        "SECONDS": {"block": None, "text": "2"}},
             "options": {}}]}
]


# ['instruction', 'lastInstruction', 'textReporter', 'numberReporter', 'booleanReporter']
projectData = {
    "sprites": [
        {
            "name": "Stage",
            "isStage": True,
            "scripts": A,
            "comments": [],
            "currentCostume": 0,
            "costumes": [],
            "sounds": [],
            "volume": 100,
        },
        {
            "name": "Sprite1",
            "isStage": False,
            "scripts": [],
            "comments": [],
            "currentCostume": 0,
            "costumes": [],
            "sounds": [],
            "localVariables": [
                {
                    "name": "loc var",
                    "currentValue": "www",
                    "monitor": None,
                }
            ],
            "localLists": [],
            "volume": 100,
            "layerOrder": 1,
            "visible": True,
            "position": [77,0],
            "size": 100,
            "direction": 90,
            "draggable": True,
            "rotationStyle": "all around",
        },
        {
            "name": "Sprite6",
            "isStage": False,
            "scripts": [],
            "comments": [],
            "currentCostume": 0,
            "costumes": [],
            "sounds": [],
            "localVariables": [],
            "localLists": [],
            "volume": 100,
            "layerOrder": 1,
            "visible": True,
            "position": [0,0],
            "size": 100,
            "direction": 90,
            "draggable": True,
            "rotationStyle": "all around",
        },
    ],
    "globalVariables": [
        {
            "name": "score",
            "currentValue": "Günter Jüchen",
            "isCloudVariable": True,
        },
        {
            "name": "var",
            "currentValue": "",
            "isCloudVariable": False,
        },
    ],
    "globalLists": [
        {"name": "list", "currentValue": []},
    ],
    "tempo": 60,
    "videoTransparency": 0,
    "videoState": "off",
    "textToSpeechLanguage": None,
#['x position', 'y position', 'direction', 'bubble width', 'bubble height', 'x stretch', 'y stretch', 
# '[EFFECT] sprite effect', 'tint color', 'visible?', 'layer', 'costume [PROPERTY]', 'backdrop [PROPERTY]', 'size', 
# '[EFFECT] sound effect', 'volume', 'answer', 'mouse down?', 'mouse clicked?', 'mouse x', 'mouse y', 
# 'clipboard item', 'draggable?', 'loudness', 'loud?', 'timer', 'current [PROPERTY]', 'days since 2000', 'username', 'logged in?', 'value of [VARIABLE]', 'value of [LIST]']
    "monitors": [
 #{'opcode': 'clipboard item',
 # 'options': {},
 # 'position': [10, 10],
 # 'spriteName': 'Sprite1',
 # 'visible': True},
 #{'opcode': 'draggable?',
 # 'options': {},
 # 'position': [10, 10],
 # 'spriteName': 'Sprite1',
 # 'visible': True},
 #{'opcode': 'loudness',
 # 'options': {},
 # 'position': [10, 10],
 # 'spriteName': 'Sprite1',
 # 'visible': True},
 #{'opcode': 'loud?',
 # 'options': {},
 # 'position': [10, 10],
 # 'spriteName': 'Sprite1',
 # 'visible': True},
 #{'opcode': 'timer',
 # 'options': {},
 # 'position': [10, 10],
 # 'spriteName': 'Sprite1',
 # 'visible': True},
#
 #{'opcode': 'current [PROPERTY]',
 # 'options': {"PROPERTY": "YEAR"},
 # 'position': [10, 10],
 # 'spriteName': 'Sprite1',
 # 'visible': True},
 #{'opcode': 'current [PROPERTY]',
 # 'options': {"PROPERTY": "MONTH"},
 # 'position': [10, 10],
 # 'spriteName': 'Sprite1',
 # 'visible': True},
 #{'opcode': 'current [PROPERTY]',
 # 'options': {"PROPERTY": "DATE"},
 # 'position': [10, 10],
 # 'spriteName': 'Sprite1',
 # 'visible': True},
 #{'opcode': 'current [PROPERTY]',
 # 'options': {"PROPERTY": "DAYOFWEEK"},
 # 'position': [10, 10],
 # 'spriteName': 'Sprite1',
 # 'visible': True},
 #{'opcode': 'current [PROPERTY]',
 # 'options': {"PROPERTY": "HOUR"},
 # 'position': [10, 10],
 # 'spriteName': 'Sprite1',
 # 'visible': True},
 #{'opcode': 'current [PROPERTY]',
 # 'options': {"PROPERTY": "MINUTE"},
 # 'position': [10, 10],
 # 'spriteName': 'Sprite1',
 # 'visible': True},
 #{'opcode': 'current [PROPERTY]',
 # 'options': {"PROPERTY": "SECOND"},
 # 'position': [10, 10],
 # 'spriteName': 'Sprite1',
 # 'visible': True},
 #{'opcode': 'current [PROPERTY]',
 # 'options': {"PROPERTY": "TIMESTAMP"},
 # 'position': [10, 10],
 # 'spriteName': 'Sprite1',
 # 'visible': True},
#
#
 #{'opcode': 'days since 2000',
 # 'options': {},
 # 'position': [10, 10],
 # 'spriteName': 'Sprite1',
 # 'visible': True},
 #{'opcode': 'username',
 # 'options': {},
 # 'position': [10, 10],
 # 'spriteName': 'Sprite1',
 # 'visible': True},
 #{'opcode': 'logged in?',
 # 'options': {},
 # 'position': [10, 10],
 # 'spriteName': 'Sprite1',
 # 'visible': True},
 #{'opcode': 'value of [VARIABLE]',
 # 'options': {"VARIABLE": "var"},
 # 'position': [10, 10],
 # 'spriteName': None,
 # 'visible': True,
 # "sliderMin": 0,
 # "sliderMax": 100,
 # "onlyIntegers": True,
 #},
 #{'opcode': 'value of [VARIABLE]',
 # 'options': {"VARIABLE": "loc var"},
 # 'position': [10, 10],
 # 'spriteName': "Sprite1",
 # 'visible': True,
 # "sliderMin": 0,
 # "sliderMax": 100,
 # "onlyIntegers": True,
#},
 {'opcode': 'value of [LIST]',
  'options': {"LIST": "list"},
  'position': [10, 10],
  'spriteName': None,
  'visible': True,
  "size": [0,0],
  }
 ],
 
    "extensionData": {},
    "extensions": ["jgJSON"],
}

from pypenguin import validateProject, deoptimizeAndCompressProject
from pypenguin.helper_functions import writeJSONFile, pp

validateProject(projectData=projectData)
#pp(projectData)

writeJSONFile(
    filePath = "temp2.json",
    data     = projectData
)

writeJSONFile(
    filePath = "project/project.json",
    data     = projectData
)

deoptimizeAndCompressProject(
    optimizedProjectDir = "project",
    projectFilePath     = "export.pmp",
    temporaryDir        = "temporary",
    writeDebugFiles     = True,
)
