scripts = [
    {'position': [0, 0],
 'blocks': [{'opcode': 'when green flag clicked', 'inputs': {}, 'options': {}},
            {'opcode': 'set [VARIABLE] to (VALUE)',
             'inputs': {'VALUE': {'block': None, 'text': '0'}},
             'options': {'VARIABLE': 'score'}},
            {'opcode': 'set [VARIABLE] to (VALUE)',
             'inputs': {'VALUE': {'block': None, 'text': '10'}},
             'options': {'VARIABLE': 'timer'}},
            {'opcode': 'add (ITEM) to [LIST]',
             'inputs': {'ITEM': {'block': None, 'text': 'Player 1'}},
             'options': {'LIST': 'players'}},
            {'opcode': 'delete (INDEX) of [LIST]',
             'inputs': {'INDEX': {'block': {'opcode': 'value of [VARIABLE]',
                                            'inputs': {},
                                            'options': {'VARIABLE': 'all'}},
                                  'text': ''}},
             'options': {'LIST': 'points'}},
            {'opcode': 'ask (QUESTION) and wait',
             'inputs': {'QUESTION': {'block': None,
                                     'text': 'What is your name?'}},
             'options': {}},
            {'opcode': 'say (MESSAGE) for (SECONDS) seconds',
             'inputs': {'MESSAGE': {'block': {'opcode': 'join (STRING1) '
                                                        '(STRING2)',
                                              'inputs': {'STRING1': {'block': None,
                                                                     'text': 'Hello, '},
                                                         'STRING2': {'block': {'opcode': 'answer',
                                                                               'inputs': {},
                                                                               'options': {}},
                                                                     'text': ''}},
                                              'options': {}},
                                    'text': ''},
                        'SECONDS': {'block': None, 'text': '2'}},
             'options': {}},
            {'opcode': 'broadcast ([MESSAGE])',
             'inputs': {'MESSAGE': {'block': None, 'option': 'start game'}},
             'options': {}},
            {'opcode': 'create clone of ([TARGET])',
             'inputs': {'TARGET': {'block': None, 'option': '_myself_'}},
             'options': {}},
            {'opcode': 'play sound ([SOUND]) until done',
             'inputs': {'SOUND': {'block': None, 'option': 'pop'}},
             'options': {}},
            {'opcode': 'when I start as a clone', 'inputs': {}, 'options': {}},
            {'opcode': 'value of [VARIABLE]',
             'inputs': {},
             'options': {'VARIABLE': 'go to'}},
            {'opcode': 'set [VARIABLE] to (VALUE)',
             'inputs': {'VALUE': {'block': {'opcode': 'pick random (OPERAND1) '
                                                      'to (OPERAND2)',
                                            'inputs': {'OPERAND1': {'block': None,
                                                                    'text': '1'},
                                                       'OPERAND2': {'block': None,
                                                                    'text': '5'}},
                                            'options': {}},
                                  'text': ''}},
             'options': {'VARIABLE': 'points'}},
            {'opcode': 'say (MESSAGE) for (SECONDS) seconds',
             'inputs': {'MESSAGE': {'block': {'opcode': 'join (STRING1) '
                                                        '(STRING2)',
                                              'inputs': {'STRING1': {'block': None,
                                                                     'text': 'Points: '},
                                                         'STRING2': {'block': {'opcode': 'value '
                                                                                         'of '
                                                                                         '[VARIABLE]',
                                                                               'inputs': {},
                                                                               'options': {'VARIABLE': 'points'}},
                                                                     'text': ''}},
                                              'options': {}},
                                    'text': ''},
                        'SECONDS': {'block': None, 'text': '2'}},
             'options': {}},
            {'opcode': 'delete this clone', 'inputs': {}, 'options': {}},
            {'opcode': 'value of [VARIABLE]',
             'inputs': {},
             'options': {'VARIABLE': 'when'}},
            {'opcode': 'value of [VARIABLE]',
             'inputs': {},
             'options': {'VARIABLE': 'repeat until'}},
            {'opcode': 'change [VARIABLE] by (VALUE)',
             'inputs': {'VALUE': {'block': None, 'text': '-1'}},
             'options': {'VARIABLE': 'timer'}},
            {'opcode': 'wait (SECONDS) seconds',
             'inputs': {'SECONDS': {'block': None, 'text': '1'}},
             'options': {}},
            {'opcode': 'value of [VARIABLE]',
             'inputs': {},
             'options': {'VARIABLE': 'end'}},
            {'opcode': 'value of [VARIABLE]',
             'inputs': {},
             'options': {'VARIABLE': 'if'}},
            {'opcode': 'say (MESSAGE) for (SECONDS) seconds',
             'inputs': {'MESSAGE': {'block': None, 'text': 'You win!'},
                        'SECONDS': {'block': None, 'text': '2'}},
             'options': {}},
            {'opcode': 'value of [VARIABLE]',
             'inputs': {},
             'options': {'VARIABLE': 'else'}},
            {'opcode': 'say (MESSAGE) for (SECONDS) seconds',
             'inputs': {'MESSAGE': {'block': None, 'text': 'Game over!'},
                        'SECONDS': {'block': None, 'text': '2'}},
             'options': {}},
            {'opcode': 'value of [VARIABLE]',
             'inputs': {},
             'options': {'VARIABLE': 'end'}},
            {'opcode': 'delete (INDEX) of [LIST]',
             'inputs': {'INDEX': {'block': {'opcode': 'value of [VARIABLE]',
                                            'inputs': {},
                                            'options': {'VARIABLE': 'all'}},
                                  'text': ''}},
             'options': {'LIST': 'players'}},
            {'opcode': 'value of [VARIABLE]',
             'inputs': {},
             'options': {'VARIABLE': 'define custom'}},
            {'opcode': 'change [VARIABLE] by (VALUE)',
             'inputs': {'VALUE': {'block': {'opcode': 'value of [VARIABLE]',
                                            'inputs': {},
                                            'options': {'VARIABLE': 'points'}},
                                  'text': ''}},
             'options': {'VARIABLE': 'score'}}]}
]


# ['instruction', 'lastInstruction', 'textReporter', 'numberReporter', 'booleanReporter']
projectData = {
    "sprites": [
        {
            "name": "Stage",
            "isStage": True,
            "scripts": [],
            "comments": [],
            "currentCostume": 0,
            "costumes": [],
            "sounds": [],
            "volume": 100,
        },
        {
            "name": "Sprite1",
            "isStage": False,
            "scripts": scripts,
            "comments": [],
            "currentCostume": 0,
            "costumes": [],
            "sounds": [
                {
                    "name": "pop",
                    "extension": "mp3",
                    "rate": 48000,
                    "sampleCount": 1123,
                },
            ],
            "localVariables": [
                {
                    "name": "loc var",
                    "currentValue": "www",
                    "monitor": None,
                }
            ],
            "localLists": [],
            "volume": 100,
            "layerOrder": 1,
            "visible": True,
            "position": [77,0],
            "size": 100,
            "direction": 90,
            "draggable": True,
            "rotationStyle": "all around",
        },
        {
            "name": "Sprite6",
            "isStage": False,
            "scripts": [],
            "comments": [],
            "currentCostume": 0,
            "costumes": [],
            "sounds": [],
            "localVariables": [],
            "localLists": [],
            "volume": 100,
            "layerOrder": 1,
            "visible": True,
            "position": [0,0],
            "size": 100,
            "direction": 90,
            "draggable": True,
            "rotationStyle": "all around",
        },
    ],
    "globalVariables": [
        {
            "name": "score",
            "currentValue": "Günter Jüchen",
            "isCloudVariable": True,
        },
        {
            "name": "timer",
            "currentValue": "",
            "isCloudVariable": False,
        },
        {
            "name": "all",
            "currentValue": "",
            "isCloudVariable": False,
        },
        
        {
            "name": "var",
            "currentValue": "",
            "isCloudVariable": False,
        },
    ],
    "globalLists": [
        {"name": "list", "currentValue": []},
        {"name": "players", "currentValue": []},
        {"name": "points", "currentValue": []},
    ],
    "tempo": 60,
    "videoTransparency": 0,
    "videoState": "off",
    "textToSpeechLanguage": None,
    "monitors": [],
 
    "extensionData": {},
    "extensions": ["jgJSON"],
}

from pypenguin import validateProject, deoptimizeAndCompressProject
from pypenguin.helper_functions import writeJSONFile, pp

validateProject(projectData=projectData)
#pp(projectData)

writeJSONFile(
    filePath = "temp2.json",
    data     = projectData
)

writeJSONFile(
    filePath = "project/project.json",
    data     = projectData
)

deoptimizeAndCompressProject(
    optimizedProjectDir = "project",
    projectFilePath     = "export.pmp",
    temporaryDir        = "temporary",
    writeDebugFiles     = True,
)
