opcodes = {
    "pen_clear": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "erase all",
        "inputTypes": {},
        "optionTypes": {},
    },
    "pen_stamp": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "stamp",
        "inputTypes": {},
        "optionTypes": {},
    },
    "pen_setPrintFont": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "set print font to (FONT)",
        "inputTypes": {"FONT": "font"},
        "optionTypes": {},
        "menus": [{"new": "FONT", "outer": "FONT", "inner": "FONT", "menuOpcode": "pen_menu_FONT"}],
    },
    "pen_setPrintFontSize": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "set print font size to (SIZE)",
        "inputTypes": {"SIZE": "number"},
        "optionTypes": {},
    },
    "pen_setPrintFontColor": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "set print font color to (COLOR)",
        "inputTypes": {"COLOR": "color"},
        "optionTypes": {},
    },
    "pen_setPrintFontWeight": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "set print font wheight to (WEIGHT)",
        "inputTypes": {"WEIGHT": "number"},
        "optionTypes": {},
    },
    "pen_setPrintFontItalics": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "set print font italics to [ON_OFF]",
        "inputTypes": {},
        "optionTypes": {"ON_OFF": "on|off"},
        "optionTranslation": {"OPTION": "ON_OFF"},
    },
    "pen_printText": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "print (TEXT) on x: (X) y: (Y)",
        "inputTypes": {"TEXT": "text", "X": "number", "Y": "number"},
        "optionTypes": {},
    },
    "pen_preloadUriImage": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "preload image (URI) as (NAME)",
        "inputTypes": {"URI": "text", "NAME": "text"},
        "optionTypes": {},
    },
    "pen_unloadUriImage": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "unload image (NAME)",
        "inputTypes": {"NAME": "text"},
        "optionTypes": {},
    },
    "pen_drawUriImage": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "draw image (URI) at x: (X) y: (Y)",
        "inputTypes": {"URI": "text", "X": "number", "Y": "number"},
        "optionTypes": {},
    },
    "pen_drawUriImageWHR":  {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "draw image (URI) at x: (X) y: (Y) width: (WIDTH) height: (HEIGHT) pointed at: (ROTATE)",
        "inputTypes": {"URI": "text", "X": "number", "Y": "number", "WIDTH": "number", "HEIGHT": "number", "ROTATE": "number"},
        "optionTypes": {},
    },
    "pen_drawUriImageWHCX1Y1X2Y2R":  {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "draw image (URI) at x: (X) y: (Y) width: (WIDTH) height: (HEIGHT) cropping from x: (CROPX) y: (CROPY) width: (CROPWIDTH) height: (CROPHEIGHT) pointed at: (ROTATE)",
        "inputTypes": {"URI": "text", "X": "number", "Y": "number", "WIDTH": "number", "HEIGHT": "number", "CROPX": "number", "CROPY": "number", "CROPWIDTH": "number", "CROPHEIGHT": "number", "ROTATE": "number"},
        "inputTranslation": {"CROPW": "CROPWIDTH", "CROPH": "CROPHEIGHT"},
        "optionTypes": {},
    },
    "pen_drawRect": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "use (COLOR) to draw a square on x: (X) y: (Y) width: (WIDTH) height: (HEIGHT)",
        "inputTypes": {"COLOR": "color", "X": "number", "Y": "number", "WIDTH": "number", "HEIGHT": "number"},
        "optionTypes": {},
    },
    "pen_drawComplexShape": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "draw triangle (TRIANGLE) with fill (COLOR)",
        "inputTypes": {"TRIANGLE": "embeddedMenu", "COLOR": "color"},
        "inputTranslation": {"SHAPE": "TRIANGLE"},
        "optionTypes": {},
    },
}