opcodes = {
    "text_setText": {
        "type": "instruction",
        "category": "Text",
        "newOpcode": "show text (TEXT)",
        "inputTypes": {"TEXT": "text"},
        "optionTypes": {},
    },
    "text_animateText": {
        "type": "instruction",
        "category": "Text",
        "newOpcode": "[ANIMATION_TECHNIQUE] text (TEXT)",
        "inputTypes": {"TEXT": "text"},
        "optionTypes": {"ANIMATION_TECHNIQUE": "animation technique"},
        "optionTranslation": {"ANIMATE": "ANIMATION_TECHNIQUE"},
    },
    "text_clearText": {
        "type": "instruction",
        "category": "Text",
        "newOpcode": "show sprite",
        "inputTypes": {},
        "optionTypes": {},
    },
    "text_setFont": {
        "type": "instruction",
        "category": "Text",
        "newOpcode": "set font to (FONT)",
        "inputTypes": {"FONT": "font"},
        "optionTypes": {},
        "menus": [{"new": "FONT", "outer": "FONT", "inner": "FONT", "menuOpcode": "text_menu_FONT"}],
    },
    "text_setColor": {
        "type": "instruction",
        "category": "Text",
        "newOpcode": "set text color to (COLOR)",
        "inputTypes": {"COLOR": "color"},
        "optionTypes": {},
    },
    "text_setWidth": {
        "type": "instruction",
        "category": "Text",
        "newOpcode": "set width to (WIDTH) aligned [ALIGN]",
        "inputTypes": {"WIDTH": "number"},
        "optionTypes": {"ALIGN": "left|center|right"},
    },
    "text_rainbow": {
        "type": "instruction",
        "category": "Text",
        "newOpcode": "rainbow for (SECONDS) seconds",
        "inputTypes": {"SECONDS": "number"},
        "inputTranslation": {"SECS": "SECONDS"},
        "optionTypes": {},
    },
    "text_addLine": {
        "type": "instruction",
        "category": "Text",
        "newOpcode": "add line (TEXT)",
        "inputTypes": {"TEXT": "text"},
        "optionTypes": {},
    },
    "text_setOutlineWidth": {
        "type": "instruction",
        "category": "Text",
        "newOpcode": "set outline width to (WIDTH)",
        "inputTypes": {"WIDTH": "number"},
        "optionTypes": {},
    },
    "text_setOutlineColor": {
        "type": "instruction",
        "category": "Text",
        "newOpcode": "set outline color to (COLOR)",
        "inputTypes": {"COLOR": "color"},
        "optionTypes": {},
    },
    "text_getVisible": {
        "type": "booleanReporter",
        "category": "Text",
        "newOpcode": "is text visible?",
        "inputTypes": {},
        "optionTypes": {},
    },
    "text_getWidth": {
        "type": "stringReporter",
        "category": "Text",
        "newOpcode": "get width of the text",
        "inputTypes": {},
        "optionTypes": {},
    },
    "text_getHeight": {
        "type": "stringReporter",
        "category": "Text",
        "newOpcode": "get height of the text",
        "inputTypes": {},
        "optionTypes": {},
    },
    "text_getDisplayedText": {
        "type": "stringReporter",
        "category": "Text",
        "newOpcode": "displayed text",
        "inputTypes": {},
        "optionTypes": {},
    },
    "text_getRender": {
        "type": "stringReporter",
        "category": "Text",
        "newOpcode": "get data uri of last rendered text",
        "inputTypes": {},
        "optionTypes": {},
    },
}