opcodes = {
    "looks_sayforsecs": {
        "type": "intruction",
        "category": "Looks",
        "newOpcode": "say (MESSAGE) for (SECONDS) seconds",
        "inputTypes": {"MESSAGE": "text", "SECONDS": "number"},
        "inputTranslation": {"SECS": "SECONDS"},
        "optionTypes": {},
    },
    "looks_say": {
        "type": "instruction",
        "category": "Looks",
        "newOpcode": "say (MESSAGE)",
        "inputTypes": {"MESSAGE": "text"},
        "optionTypes": {},
    },
    "looks_thinkforsecs": {
        "type": "intruction",
        "category": "Looks",
        "newOpcode": "think (MESSAGE) for (SECONDS) seconds",
        "inputTypes": {"MESSAGE": "text", "SECONDS": "number"},
        "inputTranslation": {"SECS": "SECONDS"},
        "optionTypes": {},
    },
    "looks_think": {
        "type": "instruction",
        "category": "Looks",
        "newOpcode": "think (MESSAGE)",
        "inputTypes": {"MESSAGE": "text"},
        "optionTypes": {},
    },
    "looks_stoptalking": {
        "type": "instruction",
        "category": "Looks",
        "newOpcode": "stop speaking",
        "inputTypes": {},
        "optionTypes": {},
    },
    "looks_setFont": {
        "type": "instruction",
        "category": "Looks",
        "newOpcode": "set font to (FONT) with font size (FONT-SIZE)",
        "inputTypes": {"FONT": "text", "FONT-SIZE": "number"},
        "inputTranslation": {"font": "FONT", "size": "FONT-SIZE"},
        "optionTypes": {},
    },
    "looks_setColor": {
        "type": "instruction",
        "category": "Looks",
        "newOpcode": "set [PROPERTY] color to (COLOR)",
        "inputTypes": {"COLOR": "color"},
        "inputTranslation": {"color": "COLOR"},
        "optionTypes": {"PROPERTY": "text bubble color property"},
        "optionTranslation": {"prop": "PROPERTY"},
    },
    "looks_setShape": {
        "type": "instruction",
        "category": "Looks",
        "newOpcode": "set text bubble [PROPERTY] to (VALUE)",
        "inputTypes": {"VALUE": "number"},
        "inputTranslation": {"color": "VALUE"},
        "optionTypes": {"PROPERTY": "text bubble property"},
        "optionTranslation": {"prop": "PROPERTY"},
    },
    "looks_sayWidth": {
        "type": "instruction",
        "category": "Looks",
        "newOpcode": "bubble width",
        "inputTypes": {},
        "optionTypes": {},
    },
    "looks_sayHeight": {
        "type": "instruction",
        "category": "Looks",
        "newOpcode": "bubble height",
        "inputTypes": {},
        "optionTypes": {},
    },

}