opcodes = {
    "sensing_touchingobject": {
        "type": "booleanReporter",
        "category": "Sensing",
        "newOpcode": "touching ([OBJECT]) ?",
        "inputTypes": {"OBJECT": "half-inclusive touchable object"},
        "optionTypes": {},
        #"optionTypes": {"OBJECT": "half-inclusive touchable object"},
        "menus": [{"new": "OBJECT", "outer": "TOUCHINGOBJECTMENU", "inner": "TOUCHINGOBJECTMENU", "menuOpcode": "sensing_touchingobjectmenu"}],
    },
    "sensing_objecttouchingobject": {
        "type": "booleanReporter",
        "category": "Sensing",
        "newOpcode": "([OBJECT]) touching ([SPRITE]) ?",
        "inputTypes": {},
        "optionTypes": {"OBJECT": "inclusive touchable object", "SPRITE": "touchable sprite"},
        "menus": [
            {"new": "OBJECT", "outer": "FULLTOUCHINGOBJECTMENU",   "inner": "FULLTOUCHINGOBJECTMENU",   "menuOpcode": "sensing_fulltouchingobjectmenu"   },
            {"new": "SPRITE", "outer": "SPRITETOUCHINGOBJECTMENU", "inner": "SPRITETOUCHINGOBJECTMENU", "menuOpcode": "sensing_touchingobjectmenusprites"},
        ],
    },
    "sensing_objecttouchingclonesprite": {
        "type": "booleanReporter",
        "category": "Sensing",
        "newOpcode": "([OBJECT]) touching clone of ([SPRITE]) ?",
        "inputTypes": {},
        "optionTypes": {"OBJECT": "inclusive touchable object", "SPRITE": "touchable sprite"},
        "menus": [
            {"new": "OBJECT", "outer": "FULLTOUCHINGOBJECTMENU",   "inner": "FULLTOUCHINGOBJECTMENU",   "menuOpcode": "sensing_fulltouchingobjectmenu"   },
            {"new": "SPRITE", "outer": "SPRITETOUCHINGOBJECTMENU", "inner": "SPRITETOUCHINGOBJECTMENU", "menuOpcode": "sensing_touchingobjectmenusprites"},
        ],
    },
    "sensing_touchingcolor": {
        "type": "booleanReporter",
        "category": "Sensing",
        "newOpcode": "touching color (COLOR) ?",
        "inputTypes": {"COLOR": "color"},
        "optionTypes": {},
    },
    "sensing_coloristouchingcolor": {
        "type": "booleanReporter",
        "category": "Sensing",
        "newOpcode": "color (COLOR1) is touching color (COLOR2) ?",
        "inputTypes": {"COLOR1": "color", "COLOR2": "color"},
        "inputTranslation": {"COLOR": "COLOR1"},
        "optionTypes": {},
    },
    "sensing_getxyoftouchingsprite": {
        "type": "textReporter",
        "category": "Sensing",
        "newOpcode": "[COORDINATE] of touching ([OBJECT]) point",
        "inputTypes": {},
        "optionTypes": {"COORDINATE": "coordinate", "OBJECT": "exclusive touchable object"},
        "optionTranslation": {"XY": "COORDINATE"},
        "menus": [{"new": "OBJECT", "outer": "SPRITE", "inner": "DISTANCETOMENU", "menuOpcode": "sensing_distancetomenu"}],
    },
    "sensing_distanceto": {
        "type": "textReporter",
        "category": "Sensing",
        "newOpcode": "distance to ([OBJECT])",
        "inputTypes": {},
        "optionTypes": {"OBJECT": "exclusive touchable object"},
        "menus": [{"new": "OBJECT", "outer": "DISTANCETOMENU", "inner": "DISTANCETOMENU", "menuOpcode": "sensing_distancetomenu"}],
    },
}